### PR TITLE
Port to aioboto3

### PR DESCRIPTION
**Pull request by lpsinger**
FIXME: depends on this upstream PR.
https://github.com/ClearcodeHQ/pytest-dynamodb/pull/1297

### CODE REVIEW

**Comment by lpsinger** [comment]
I don't know if we can or should support both boto3 and aioboto3.

**Review by swyatt7 — APPROVED** [review]
Looks good. I pulled it/installed and ran the test.

**Comment by lpsinger** [comment]
> Looks good. I pulled it/installed and ran the test.

Thanks. I'm going to move this to Draft status while we wait to hear from upstream. I've found the ClearcodeHQ maintainers to be pretty responsive in the past.

**Comment by jak574** [comment]
I missed this somehow. So I guess my own PR is pointless. Sorry!

**Review by jak574 — APPROVED** [review]
The ultimate test: I did this conversion myself, wrote code that used it, then realized you'd already done it, used your code instead and it still worked.

**Comment by jak574** [comment]
> I don't know if we can or should support both boto3 and aioboto3.

I think this depends on whether you expect this code to be used more broadly. If you look at what I did in PR #6, I just added versions of the classes prefixed by Async. So supporting both would be pretty trivial I think.

**Comment by lpsinger** [comment]
Unfortunately, there is no simple way to support both boto3 and aioboto3 without having two duplicate copies of this code. This is because in Python `await` is more than just syntactic sugar; it changes the function into a coroutine and so anything that calls it must also be a coroutine. By contrast, in JavaScript, `async`/`await` is just shorthand for promises which you can use in any ordinary function. In JavaScript, you can `await` anything in Javascript, even things that are not promises; awaiting a value that is not a Promise just returns that value. So you can write functions that "maybe" await things in JavaScript but not in Python.

**Pull request merged**
